# Generated by Django 2.2.6 on 2019-11-07 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserObjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'userobjects',
                'unique_together': {('username', 'password')},
            },
        ),
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('ticketid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('ticket_desc', models.CharField(max_length=128)),
                ('notes', models.CharField(default='', max_length=128)),
                ('ticket_category', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('userobjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.UserObjects')),
            ],
            options={
                'db_table': 'ticketdetails',
            },
        ),
        migrations.CreateModel(
            name='NotesDetails',
            fields=[
                ('notesid', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=128)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketDetails')),
                ('userobjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.UserObjects')),
            ],
            options={
                'db_table': 'notesdetails',
            },
        ),
    ]
